# Generated by Django 4.2.3 on 2023-07-24 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'ARCHIVED'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10, null=True)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'ARCHIVED'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10, null=True)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('story_line', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
